### ISSUE TITLE
Make checkboxes styling more specific to SEO forms

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/seo_meta#17]
Currently, seo_meta.admin.css styles checkboxes such that all checkboxes on the form are affected, rather than just SEO Meta form checkboxes.

Recommend changing:
```css
.form-checkboxes {
  display: flex;
}
```
To something like:
```css
#edit-seo-meta .form-checkboxes {
  display: flex;
}
```
